"""added profile pic

Revision ID: 510f06a6e0ba
Revises: 5310d132f1be
Create Date: 2024-08-26 14:16:39.602031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510f06a6e0ba'
down_revision = '5310d132f1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
