"""empty message

Revision ID: 934732609bcf
Revises: 2410a5be2674
Create Date: 2024-08-16 11:35:16.012160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934732609bcf'
down_revision = '2410a5be2674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
